### ISSUE TITLE
Clean up artifacts as you go

### ISSUE THREAD

**Issue by jeremyspykerman** [spykermj/container-registry-jmeter-testplan#3]
As written, this performance test does not clean up the artifacts written to the remote repository. This means that the storage requirements for the target container repository grow very rapidly.

Adding a step to delete the remote artifacts as you go would improve this situation greatly. Unfortunately, different container registries will most likely handle deletion differently as it does not seem to be part of a standard.

**Comment by spykermj** [comment]
closed by the last merge to main
